# Generated by Django 3.0.5 on 2020-07-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.TextField()),
                ('name', models.TextField()),
                ('date', models.DateTimeField()),
                ('first_period', models.DateTimeField()),
                ('second_period', models.DateTimeField()),
                ('iin', models.IntegerField(max_length=12)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
