# Generated by Django 3.0.5 on 2020-07-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_auto_20200721_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='iin',
            field=models.CharField(max_length=12),
        ),
    ]
